kind: project
status:
  state: online
metadata:
  name: workflow-override
  created: '2026-01-11T19:20:18.833000'
spec:
  owner: xingsheng
  load_source_on_run: false
  conda: ''
  desired_state: online
  build:
    source_code_target_dir: /home/mlrun_code/
    image: .mlrun-project-image-workflow-override
    requirements:
    - langchain==0.2.17
    - openai==1.58.1
    - langchain_community==0.2.19
    commands:
    - pip install mlrun langchain==0.2.17 openai==1.58.1 langchain_community==0.2.19
    base_image: mlrun/mlrun-kfp
  functions:
  - url: ./src/test-image.py
    name: test-image
    kind: job
    image: .mlrun-project-image-workflow-override
  - url: hub://structured_data_generator
    name: structured-data-generator
    kind: job
    image: .mlrun-project-image-workflow-override
  origin_url: git://github.com/xsqian/workflow-overrite-default-image.git#refs/heads/main
  params:
    build_image: false
    source: git://github.com/xsqian/workflow-overrite-default-image.git#main
    default_image: .mlrun-project-image-workflow-override
  default_image: .mlrun-project-image-workflow-override
  workflows:
  - image: .mlrun-project-image-workflow-override
    name: test-image-in-workflow
    path: src/workflow-image.py
  source: git://github.com/xsqian/workflow-overrite-default-image.git#main
